spring:
  datasource:
    druid:
      url: jdbc:mysql://47.100.93.1:3306/SecurityDemo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: qz1941131
  thymeleaf:
    cache: false
#    开启mvc视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:com/example/securitydemo/mapper/*.xml
