spring:
  datasource:
    druid:
      url: jdbc:mysql://47.100.93.1:3306/SecurityDemo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: qz1941131
mybatis:
  mapper-locations: classpath:com/example/securitydemo/mapper/*.xml
